// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiWVCxntTtKP0aNaQm-rFkTm63xRzWz88',
    appId: '1:284217630302:web:7d02d0c6a721ad4ca21ecf',
    messagingSenderId: '284217630302',
    projectId: 'notetaskyver2',
    authDomain: 'notetaskyver2.firebaseapp.com',
    storageBucket: 'notetaskyver2.firebasestorage.app',
    measurementId: 'G-3V06M28GDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUaf1OadQ1xiyboeybAZUhISAP0JRfrTc',
    appId: '1:284217630302:android:c9e3dcce4abc3079a21ecf',
    messagingSenderId: '284217630302',
    projectId: 'notetaskyver2',
    storageBucket: 'notetaskyver2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXmBlnLrUeDEaoEc7QcWQBFpHYrzqQLCA',
    appId: '1:284217630302:ios:e15fb3b9be686543a21ecf',
    messagingSenderId: '284217630302',
    projectId: 'notetaskyver2',
    storageBucket: 'notetaskyver2.firebasestorage.app',
    iosBundleId: 'com.example.noteTaskyVer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXmBlnLrUeDEaoEc7QcWQBFpHYrzqQLCA',
    appId: '1:284217630302:ios:e15fb3b9be686543a21ecf',
    messagingSenderId: '284217630302',
    projectId: 'notetaskyver2',
    storageBucket: 'notetaskyver2.firebasestorage.app',
    iosBundleId: 'com.example.noteTaskyVer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiWVCxntTtKP0aNaQm-rFkTm63xRzWz88',
    appId: '1:284217630302:web:dad9a002c5704162a21ecf',
    messagingSenderId: '284217630302',
    projectId: 'notetaskyver2',
    authDomain: 'notetaskyver2.firebaseapp.com',
    storageBucket: 'notetaskyver2.firebasestorage.app',
    measurementId: 'G-QF2MW6GKP2',
  );
}
